<?php

namespace Database\Seeders;

use App\Models\WorkOrder;
use Illuminate\Database\Seeder;

class WorkOrderSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $workOrders = [
            [
                'no_work_order' => 'WO-2024-001',
                'tgl_work_order' => '2024-01-15',
                'rincian_pekerjaan' => 'Perbaikan sistem AC di lantai 3 yang mengalami kebocoran refrigerant',
                'department_tujuan' => 'Engineering',
                'lokasi' => 'Gedung A - Lantai 3',
                'tenant_id' => 'TEN-001',
                'priority_type' => 'urgent',
                'urgent_sub_type' => 'accident',
                'prioritas' => 'Urgent - Accident',
                'status_tiket' => 'Executed',
                'user_requester' => 'Ahmad Subagyo',
                'modified_user' => 1,
                'keterangan' => 'Sudah diperbaiki dan berfungsi normal',
                'incident_photos' => ['photos/ac-leak-1.jpg', 'photos/ac-leak-2.jpg'],
            ],
            [
                'no_work_order' => 'WO-2024-002',
                'tgl_work_order' => '2024-01-18',
                'rincian_pekerjaan' => 'Penggantian lampu LED di area parkir basement',
                'department_tujuan' => 'Facility',
                'lokasi' => 'Basement Parkir',
                'tenant_id' => 'TEN-002',
                'priority_type' => 'normal',
                'urgent_sub_type' => null,
                'prioritas' => 'Normal',
                'status_tiket' => 'Executed',
                'user_requester' => 'Siti Rahayu',
                'modified_user' => 1,
                'keterangan' => '50 unit lampu sudah diganti',
                'incident_photos' => ['photos/parking-light.jpg'],
            ],
            [
                'no_work_order' => 'WO-2024-003',
                'tgl_work_order' => '2024-02-03',
                'rincian_pekerjaan' => 'Perbaikan lift penumpang yang mengalami error pada panel kontrol',
                'department_tujuan' => 'Engineering',
                'lokasi' => 'Gedung B - Lift Utama',
                'tenant_id' => 'TEN-001',
                'priority_type' => 'urgent',
                'urgent_sub_type' => 'accident',
                'prioritas' => 'Urgent - Accident',
                'status_tiket' => 'Executed',
                'user_requester' => 'Budi Santoso',
                'modified_user' => 1,
                'keterangan' => 'Panel kontrol sudah diganti dan lift beroperasi normal',
                'incident_photos' => ['photos/electric-panel-1.jpg', 'photos/electric-panel-2.jpg', 'photos/electric-panel-3.jpg'],
            ],
            [
                'no_work_order' => 'WO-2024-004',
                'tgl_work_order' => '2024-02-10',
                'rincian_pekerjaan' => 'Pengecatan ulang dinding lobby utama gedung A',
                'department_tujuan' => 'Facility',
                'lokasi' => 'Lobby Gedung A',
                'tenant_id' => 'TEN-003',
                'priority_type' => 'normal',
                'urgent_sub_type' => null,
                'prioritas' => 'Normal',
                'status_tiket' => 'Pending HOD',
                'user_requester' => 'Dewi Lestari',
                'modified_user' => null,
                'keterangan' => 'Menunggu persetujuan budget',
                'incident_photos' => [],
            ],
            [
                'no_work_order' => 'WO-2024-005',
                'tgl_work_order' => '2024-02-15',
                'rincian_pekerjaan' => 'Inspeksi dan perbaikan sistem sprinkler kebakaran',
                'department_tujuan' => 'HSE',
                'lokasi' => 'Seluruh Area Gedung',
                'tenant_id' => 'TEN-001',
                'priority_type' => 'urgent',
                'urgent_sub_type' => 'owner',
                'prioritas' => 'Urgent - Owner',
                'status_tiket' => 'Executed',
                'user_requester' => 'Eko Prasetyo',
                'modified_user' => 1,
                'keterangan' => 'Semua sprinkler berfungsi dengan baik',
                'incident_photos' => ['photos/sprinkler-inspection.jpg'],
            ],
            [
                'no_work_order' => 'WO-2024-006',
                'tgl_work_order' => '2024-02-20',
                'rincian_pekerjaan' => 'Perbaikan atap bocor di ruang server lantai 2',
                'department_tujuan' => 'Engineering',
                'lokasi' => 'Gedung A - Lantai 2',
                'tenant_id' => 'TEN-001',
                'priority_type' => 'urgent',
                'urgent_sub_type' => 'accident',
                'prioritas' => 'Urgent - Accident',
                'status_tiket' => 'Executed',
                'user_requester' => 'Fajar Nugroho',
                'modified_user' => 1,
                'keterangan' => 'Atap sudah diperbaiki, tidak ada kebocoran',
                'incident_photos' => ['photos/roof-leak-1.jpg', 'photos/roof-leak-2.jpg'],
            ],
            [
                'no_work_order' => 'WO-2024-007',
                'tgl_work_order' => '2024-03-01',
                'rincian_pekerjaan' => 'Instalasi CCTV baru di area loading dock',
                'department_tujuan' => 'Security',
                'lokasi' => 'Loading Dock',
                'tenant_id' => 'TEN-004',
                'priority_type' => 'normal',
                'urgent_sub_type' => null,
                'prioritas' => 'Normal',
                'status_tiket' => 'Executed',
                'user_requester' => 'Gita Permata',
                'modified_user' => 1,
                'keterangan' => '8 kamera CCTV terpasang dan berfungsi',
                'incident_photos' => ['photos/cctv-installation.jpg'],
            ],
            [
                'no_work_order' => 'WO-2024-008',
                'tgl_work_order' => '2024-03-05',
                'rincian_pekerjaan' => 'Perbaikan sistem fire alarm yang sering false alarm',
                'department_tujuan' => 'HSE',
                'lokasi' => 'Gedung C - Semua Lantai',
                'tenant_id' => 'TEN-001',
                'priority_type' => 'urgent',
                'urgent_sub_type' => 'owner',
                'prioritas' => 'Urgent - Owner',
                'status_tiket' => 'Pending HOD',
                'user_requester' => 'Hendra Wijaya',
                'modified_user' => null,
                'keterangan' => 'Perlu kalibrasi sensor smoke detector',
                'incident_photos' => ['photos/fire-alarm.jpg'],
            ],
            [
                'no_work_order' => 'WO-2024-009',
                'tgl_work_order' => '2024-03-10',
                'rincian_pekerjaan' => 'Penggantian karpet di ruang meeting lantai 5',
                'department_tujuan' => 'Facility',
                'lokasi' => 'Gedung A - Lantai 5',
                'tenant_id' => 'TEN-002',
                'priority_type' => 'normal',
                'urgent_sub_type' => null,
                'prioritas' => 'Normal',
                'status_tiket' => 'Rejected',
                'user_requester' => 'Indah Sari',
                'modified_user' => 1,
                'keterangan' => 'Budget ditolak, akan diajukan ulang tahun depan',
                'incident_photos' => [],
            ],
            [
                'no_work_order' => 'WO-2024-010',
                'tgl_work_order' => '2024-03-15',
                'rincian_pekerjaan' => 'Perbaikan pintu otomatis yang macet di entrance utama',
                'department_tujuan' => 'Engineering',
                'lokasi' => 'Main Entrance',
                'tenant_id' => 'TEN-001',
                'priority_type' => 'urgent',
                'urgent_sub_type' => 'accident',
                'prioritas' => 'Urgent - Accident',
                'status_tiket' => 'Executed',
                'user_requester' => 'Joko Susilo',
                'modified_user' => 1,
                'keterangan' => 'Motor penggerak sudah diganti',
                'incident_photos' => ['photos/automatic-door.jpg'],
            ],
            [
                'no_work_order' => 'WO-2024-011',
                'tgl_work_order' => '2024-03-20',
                'rincian_pekerjaan' => 'Pemeliharaan rutin generator set backup',
                'department_tujuan' => 'Engineering',
                'lokasi' => 'Room Genset',
                'tenant_id' => 'TEN-001',
                'priority_type' => 'normal',
                'urgent_sub_type' => null,
                'prioritas' => 'Normal',
                'status_tiket' => 'Executed',
                'user_requester' => 'Kurniawan Adi',
                'modified_user' => 1,
                'keterangan' => 'Oil filter dan air filter sudah diganti',
                'incident_photos' => ['photos/genset-maintenance.jpg'],
            ],
            [
                'no_work_order' => 'WO-2024-012',
                'tgl_work_order' => '2024-03-25',
                'rincian_pekerjaan' => 'Perbaikan saluran air tersumbat di pantry lantai 4',
                'department_tujuan' => 'Plumbing',
                'lokasi' => 'Gedung B - Lantai 4',
                'tenant_id' => 'TEN-003',
                'priority_type' => 'normal',
                'urgent_sub_type' => null,
                'prioritas' => 'Normal',
                'status_tiket' => 'Executed',
                'user_requester' => 'Linda Kusuma',
                'modified_user' => 1,
                'keterangan' => 'Saluran sudah lancar kembali',
                'incident_photos' => ['photos/drain-clog.jpg'],
            ],
            [
                'no_work_order' => 'WO-2024-013',
                'tgl_work_order' => '2024-04-01',
                'rincian_pekerjaan' => 'Instalasi akses card reader di pintu darurat',
                'department_tujuan' => 'Security',
                'lokasi' => 'Emergency Exit - Semua Lantai',
                'tenant_id' => 'TEN-001',
                'priority_type' => 'urgent',
                'urgent_sub_type' => 'owner',
                'prioritas' => 'Urgent - Owner',
                'status_tiket' => 'Executed',
                'user_requester' => 'Mulyanto',
                'modified_user' => 1,
                'keterangan' => '12 card reader terpasang dan terintegrasi',
                'incident_photos' => ['photos/card-reader.jpg'],
            ],
            [
                'no_work_order' => 'WO-2024-014',
                'tgl_work_order' => '2024-04-05',
                'rincian_pekerjaan' => 'Perbaikan escalator yang bergetar tidak normal',
                'department_tujuan' => 'Engineering',
                'lokasi' => 'Gedung A - Escalator Utara',
                'tenant_id' => 'TEN-001',
                'priority_type' => 'urgent',
                'urgent_sub_type' => 'accident',
                'prioritas' => 'Urgent - Accident',
                'status_tiket' => 'Executed',
                'user_requester' => 'Ningsih Rahayu',
                'modified_user' => 1,
                'keterangan' => 'Bearing dan chain sudah diganti',
                'incident_photos' => ['photos/escalator-repair-1.jpg', 'photos/escalator-repair-2.jpg'],
            ],
            [
                'no_work_order' => 'WO-2024-015',
                'tgl_work_order' => '2024-04-10',
                'rincian_pekerjaan' => 'Pengecatan marka jalan di area parkir outdoor',
                'department_tujuan' => 'Facility',
                'lokasi' => 'Outdoor Parking',
                'tenant_id' => 'TEN-002',
                'priority_type' => 'normal',
                'urgent_sub_type' => null,
                'prioritas' => 'Normal',
                'status_tiket' => 'Pending HOD',
                'user_requester' => 'Oscar Pratama',
                'modified_user' => null,
                'keterangan' => 'Menunggu jadwal pelaksanaan',
                'incident_photos' => [],
            ],
            [
                'no_work_order' => 'WO-2024-016',
                'tgl_work_order' => '2024-04-15',
                'rincian_pekerjaan' => 'Perbaikan sistem grounding panel listrik utama',
                'department_tujuan' => 'Engineering',
                'lokasi' => 'Electrical Room',
                'tenant_id' => 'TEN-001',
                'priority_type' => 'urgent',
                'urgent_sub_type' => 'accident',
                'prioritas' => 'Urgent - Accident',
                'status_tiket' => 'Executed',
                'user_requester' => 'Putra Aditya',
                'modified_user' => 1,
                'keterangan' => 'Grounding sudah sesuai standar SNI',
                'incident_photos' => ['photos/grounding-system.jpg'],
            ],
            [
                'no_work_order' => 'WO-2024-017',
                'tgl_work_order' => '2024-04-20',
                'rincian_pekerjaan' => 'Penggantian unit AHU (Air Handling Unit) di lantai 6',
                'department_tujuan' => 'Engineering',
                'lokasi' => 'Gedung B - Lantai 6',
                'tenant_id' => 'TEN-004',
                'priority_type' => 'normal',
                'urgent_sub_type' => null,
                'prioritas' => 'Normal',
                'status_tiket' => 'Rejected',
                'user_requester' => 'Rina Marlina',
                'modified_user' => 1,
                'keterangan' => 'Masih dalam garansi, akan klaim ke vendor',
                'incident_photos' => ['photos/ahu-unit.jpg'],
            ],
            [
                'no_work_order' => 'WO-2024-018',
                'tgl_work_order' => '2024-04-25',
                'rincian_pekerjaan' => 'Perbaikan waterproofing atap rooftop garden',
                'department_tujuan' => 'Facility',
                'lokasi' => 'Rooftop Garden',
                'tenant_id' => 'TEN-001',
                'priority_type' => 'normal',
                'urgent_sub_type' => null,
                'prioritas' => 'Normal',
                'status_tiket' => 'Executed',
                'user_requester' => 'Slamet Riyadi',
                'modified_user' => 1,
                'keterangan' => 'Waterproofing sudah diperbaiki dengan membran bakar',
                'incident_photos' => ['photos/waterproofing-1.jpg', 'photos/waterproofing-2.jpg'],
            ],
            [
                'no_work_order' => 'WO-2024-019',
                'tgl_work_order' => '2024-05-01',
                'rincian_pekerjaan' => 'Inspeksi dan testing sistem UPS (Uninterruptible Power Supply)',
                'department_tujuan' => 'Engineering',
                'lokasi' => 'Server Room',
                'tenant_id' => 'TEN-001',
                'priority_type' => 'urgent',
                'urgent_sub_type' => 'owner',
                'prioritas' => 'Urgent - Owner',
                'status_tiket' => 'Executed',
                'user_requester' => 'Teguh Prakoso',
                'modified_user' => 1,
                'keterangan' => 'Battery backup masih dalam kondisi baik (85%)',
                'incident_photos' => ['photos/ups-testing.jpg'],
            ],
            [
                'no_work_order' => 'WO-2024-020',
                'tgl_work_order' => '2024-05-05',
                'rincian_pekerjaan' => 'Perbaikan keramik lantai yang pecah di koridor lantai 3',
                'department_tujuan' => 'Facility',
                'lokasi' => 'Gedung A - Lantai 3',
                'tenant_id' => 'TEN-003',
                'priority_type' => 'normal',
                'urgent_sub_type' => null,
                'prioritas' => 'Normal',
                'status_tiket' => 'Pending HOD',
                'user_requester' => 'Ulfa Zahra',
                'modified_user' => null,
                'keterangan' => 'Perlu pengadaan keramik yang sama',
                'incident_photos' => ['photos/broken-tile.jpg'],
            ],
            [
                'no_work_order' => 'WO-2024-021',
                'tgl_work_order' => '2024-05-10',
                'rincian_pekerjaan' => 'Kalibrasi sistem BMS (Building Management System)',
                'department_tujuan' => 'Engineering',
                'lokasi' => 'Control Room',
                'tenant_id' => 'TEN-001',
                'priority_type' => 'normal',
                'urgent_sub_type' => null,
                'prioritas' => 'Normal',
                'status_tiket' => 'Executed',
                'user_requester' => 'Vicky Firmansyah',
                'modified_user' => 1,
                'keterangan' => 'Semua sensor sudah terkalibrasi dengan akurat',
                'incident_photos' => ['photos/bms-calibration.jpg'],
            ],
            [
                'no_work_order' => 'WO-2024-022',
                'tgl_work_order' => '2024-05-15',
                'rincian_pekerjaan' => 'Perbaikan kaca jendela pecah akibat angin kencang',
                'department_tujuan' => 'Facility',
                'lokasi' => 'Gedung C - Lantai 8',
                'tenant_id' => 'TEN-002',
                'priority_type' => 'urgent',
                'urgent_sub_type' => 'accident',
                'prioritas' => 'Urgent - Accident',
                'status_tiket' => 'Executed',
                'user_requester' => 'Wati Sulistyo',
                'modified_user' => 1,
                'keterangan' => 'Kaca tempered sudah diganti',
                'incident_photos' => ['photos/broken-window-1.jpg', 'photos/broken-window-2.jpg'],
            ],
            [
                'no_work_order' => 'WO-2024-023',
                'tgl_work_order' => '2024-05-20',
                'rincian_pekerjaan' => 'Pemasangan safety sign dan emergency exit sign baru',
                'department_tujuan' => 'HSE',
                'lokasi' => 'Seluruh Area Gedung',
                'tenant_id' => 'TEN-001',
                'priority_type' => 'normal',
                'urgent_sub_type' => null,
                'prioritas' => 'Normal',
                'status_tiket' => 'Executed',
                'user_requester' => 'Yoga Hermawan',
                'modified_user' => 1,
                'keterangan' => '45 sign sudah terpasang sesuai standar K3',
                'incident_photos' => ['photos/safety-sign.jpg'],
            ],
            [
                'no_work_order' => 'WO-2024-024',
                'tgl_work_order' => '2024-05-25',
                'rincian_pekerjaan' => 'Perbaikan pompa air tekanan rendah di lantai 7',
                'department_tujuan' => 'Plumbing',
                'lokasi' => 'Gedung B - Lantai 7',
                'tenant_id' => 'TEN-004',
                'priority_type' => 'normal',
                'urgent_sub_type' => null,
                'prioritas' => 'Normal',
                'status_tiket' => 'Pending HOD',
                'user_requester' => 'Zainal Abidin',
                'modified_user' => null,
                'keterangan' => 'Perlu replacement pompa baru',
                'incident_photos' => ['photos/water-pump.jpg'],
            ],
            [
                'no_work_order' => 'WO-2024-025',
                'tgl_work_order' => '2024-06-01',
                'rincian_pekerjaan' => 'Overhaul chiller unit untuk persiapan musim kemarau',
                'department_tujuan' => 'Engineering',
                'lokasi' => 'Chiller Plant Room',
                'tenant_id' => 'TEN-001',
                'priority_type' => 'normal',
                'urgent_sub_type' => null,
                'prioritas' => 'Normal',
                'status_tiket' => 'Executed',
                'user_requester' => 'Andi Setiawan',
                'modified_user' => 1,
                'keterangan' => 'Chiller berfungsi optimal dengan COP 5.2',
                'incident_photos' => ['photos/chiller-overhaul.jpg'],
            ],
        ];

        foreach ($workOrders as $workOrder) {
            WorkOrder::create($workOrder);
        }
    }
}
