import { Form, Head, Link } from '@inertiajs/react';
import { ArrowLeft } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { store as scheduleStore, index as scheduleIndex, update as scheduleUpdate } from '@/routes/work-data/schedule';
type WorkDataWithDept = { id_work_data: number; no_kerja: string; department?: { nama_department: string } | null };
type ScheduleWorkData = { id_schedule_wd: number; id_work_data: number; tgl_jadwal: string; jam_mulai: string | null; jam_selesai: string | null; jenis_pekerjaan: string | null; deskripsi_pekerjaan: string | null; lokasi: string | null; status_jadwal: string; catatan: string | null; rescheduled_from: number | null };
const fields = [['tgl_jadwal', 'Date', 'date'], ['jam_mulai', 'Start Time', 'time'], ['jam_selesai', 'End Time', 'time'], ['lokasi', 'Location', 'text']] as const; const types = ['Preventive', 'Corrective', 'Emergency']; const statuses = ['scheduled', 'in_progress', 'completed', 'cancelled', 'rescheduled'];
export function ScheduleForm({ workData, schedule }: { workData: WorkDataWithDept; schedule?: ScheduleWorkData }) { return <><Head title={`${schedule ? 'Edit' : 'Add'} Schedule - ${workData.no_kerja}`} /><div className="mx-auto w-full max-w-3xl space-y-6"><Link href={scheduleIndex.url({ workData: workData.id_work_data })} className="inline-flex items-center gap-2 text-sm text-neutral-500 hover:text-[#0071b7]"><ArrowLeft className="size-4" />Back to Schedules</Link><div className="rounded-2xl bg-linear-to-br from-[#0071b7] via-[#0089cc] to-[#0093dd] p-8 shadow-lg"><h1 className="text-3xl font-bold text-white">{schedule ? 'Edit Schedule' : 'Add Schedule'}</h1><p className="mt-2 text-sm text-white/80">{workData.no_kerja}</p></div><Form method="post" action={schedule ? scheduleUpdate.url({ workData: workData.id_work_data, schedule: schedule.id_schedule_wd }) : scheduleStore.url({ workData: workData.id_work_data })} className="space-y-5 rounded-2xl border border-neutral-200/60 bg-white p-6 shadow-sm dark:border-neutral-800 dark:bg-neutral-900">{({ processing }) => <><input type="hidden" name="_method" value={schedule ? 'PUT' : 'POST'} /><div className="grid gap-4 sm:grid-cols-2">{fields.map(([name, title, type]) => <div key={name}><Label htmlFor={name}>{title}</Label><Input id={name} name={name} type={type} defaultValue={(schedule as any)?.[name] || ''} className="mt-1" /></div>)}<div><Label>Type</Label><select name="jenis_pekerjaan" defaultValue={schedule?.jenis_pekerjaan || 'Preventive'} className="mt-1 w-full rounded-lg border px-3 py-2 dark:border-neutral-700 dark:bg-neutral-800 dark:text-white">{types.map(x => <option key={x}>{x}</option>)}</select></div><div><Label>Status</Label><select name="status_jadwal" defaultValue={schedule?.status_jadwal || 'scheduled'} className="mt-1 w-full rounded-lg border px-3 py-2 dark:border-neutral-700 dark:bg-neutral-800 dark:text-white">{statuses.map(x => <option key={x}>{x}</option>)}</select></div></div><div><Label>Description</Label><Textarea name="deskripsi_pekerjaan" defaultValue={schedule?.deskripsi_pekerjaan || ''} rows={4} className="mt-1" /></div><div><Label>Catatan</Label><Textarea name="catatan" defaultValue={schedule?.catatan || ''} rows={3} className="mt-1" /></div><div className="flex justify-end"><Button disabled={processing} className="bg-linear-to-r from-[#0071b7] to-[#0093dd]">{processing ? 'Saving...' : 'Save Schedule'}</Button></div></>}</Form></div></>; }
export default function ScheduleCreate({ workData }: { workData: WorkDataWithDept }) { return <ScheduleForm workData={workData} />; }
ScheduleCreate.layout = { breadcrumbs: [{ title: 'Work Data', href: '/work-data' }, { title: 'Schedules', href: '' }, { title: 'Add', href: '' }] };
