import { Form, Head, Link } from '@inertiajs/react';
import { ArrowLeft, Edit, RefreshCw } from 'lucide-react';
import { useState } from 'react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { index as scheduleIndex, edit as scheduleEdit, reschedule as scheduleReschedule } from '@/routes/work-data/schedule';
type WorkDataWithDept = { id_work_data: number; no_kerja: string; department?: { nama_department: string } | null };
type ScheduleWorkData = { id_schedule_wd: number; id_work_data: number; tgl_jadwal: string; jam_mulai: string | null; jam_selesai: string | null; jenis_pekerjaan: string | null; deskripsi_pekerjaan: string | null; lokasi: string | null; status_jadwal: string; catatan: string | null; rescheduled_from: number | null };
const colors: Record<string, string> = { scheduled: 'bg-blue-100 text-blue-700 dark:bg-blue-500/20 dark:text-blue-400', in_progress: 'bg-yellow-100 text-yellow-700 dark:bg-yellow-500/20 dark:text-yellow-400', completed: 'bg-green-100 text-green-700 dark:bg-green-500/20 dark:text-green-400', cancelled: 'bg-red-100 text-red-700 dark:bg-red-500/20 dark:text-red-400', rescheduled: 'bg-neutral-100 text-neutral-700 dark:bg-neutral-800 dark:text-neutral-300' };
export default function ScheduleShow({ workData, schedule }: { workData: WorkDataWithDept; schedule: ScheduleWorkData }) { const [open, setOpen] = useState(false); const rows = [['Date', schedule.tgl_jadwal], ['Time', `${schedule.jam_mulai || '-'} - ${schedule.jam_selesai || '-'}`], ['Type', schedule.jenis_pekerjaan || '-'], ['Location', schedule.lokasi || '-'], ['Description', schedule.deskripsi_pekerjaan || '-'], ['Catatan', schedule.catatan || '-'], ['Rescheduled From', schedule.rescheduled_from?.toString() || '-']]; return <><Head title={`Schedule - ${workData.no_kerja}`} /><div className="mx-auto w-full max-w-4xl space-y-6"><Link href={scheduleIndex.url({ workData: workData.id_work_data })} className="inline-flex items-center gap-2 text-sm text-neutral-500 hover:text-[#0071b7]"><ArrowLeft className="size-4" />Back to Schedules</Link><div className="relative overflow-hidden rounded-2xl bg-linear-to-br from-[#0071b7] via-[#0089cc] to-[#0093dd] p-8 shadow-lg"><div className="flex items-center justify-between"><div><p className="mb-2 text-sm text-white/80">Schedule Details</p><h1 className="text-3xl font-bold text-white">{workData.no_kerja}</h1></div><Badge className={`capitalize ${colors[schedule.status_jadwal] || ''}`}>{schedule.status_jadwal.replace(/_/g, ' ')}</Badge></div></div><div className="rounded-2xl border border-neutral-200/60 bg-white p-6 shadow-sm dark:border-neutral-800 dark:bg-neutral-900"><div className="grid gap-5 sm:grid-cols-2">{rows.map(([name, value]) => <div key={name} className={name === 'Description' || name === 'Catatan' ? 'sm:col-span-2' : ''}><Label className="text-xs text-neutral-500">{name}</Label><p className="mt-1 text-sm dark:text-white">{value}</p></div>)}</div><div className="mt-6 flex flex-wrap justify-end gap-3"><Link href={scheduleEdit.url({ workData: workData.id_work_data, schedule: schedule.id_schedule_wd })}><Button variant="outline"><Edit className="size-4" />Edit</Button></Link><Button onClick={() => setOpen(!open)} className="bg-linear-to-r from-[#0071b7] to-[#0093dd]"><RefreshCw className="size-4" />Reschedule</Button></div>{open && <Form method="post" action={scheduleReschedule.url({ workData: workData.id_work_data, schedule: schedule.id_schedule_wd })} className="mt-6 grid gap-4 border-t pt-6 sm:grid-cols-2 dark:border-neutral-700">{({ processing }) => <><div><Label htmlFor="tgl_jadwal">New Date</Label><Input id="tgl_jadwal" name="tgl_jadwal" type="date" required className="mt-1" /></div><div><Label htmlFor="catatan">Reason</Label><Textarea id="catatan" name="catatan" rows={2} className="mt-1" /></div><div className="sm:col-span-2 flex justify-end"><Button disabled={processing} type="submit">{processing ? 'Saving...' : 'Confirm Reschedule'}</Button></div></>}</Form>}</div></div></>; }
ScheduleShow.layout = { breadcrumbs: [{ title: 'Work Data', href: '/work-data' }, { title: 'Schedules', href: '' }, { title: 'Details', href: '' }] };
