import { Form, Head, Link } from '@inertiajs/react';
import { ArrowLeft } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { store as pekerjaStore, index as pekerjaIndex, update as pekerjaUpdate } from '@/routes/work-data/pekerja';
type WorkDataWithDept = { id_work_data: number; no_kerja: string; department?: { nama_department: string } | null };
type Department = { id_department: string; nama_department: string; kode_department: string };
type Props = { workData: WorkDataWithDept; departments: Department[] };
const roles = ['pelaksana', 'koordinator', 'pengawas']; const statuses = ['assigned', 'accepted', 'in_progress', 'completed'];
export default function PekerjaCreate({ workData }: Props) { return <WorkerForm workData={workData} />; }
export function WorkerForm({ workData, pekerja }: { workData: WorkDataWithDept; pekerja?: { id_work_data_pekerja?: number; id_employee: string | null; id_user: number | null; role_pekerja: string; status_alokasi: string; catatan: string | null } }) { return <><Head title={`${pekerja ? 'Edit' : 'Add'} Worker - ${workData.no_kerja}`} /><div className="mx-auto w-full max-w-3xl space-y-6"><Link href={pekerjaIndex.url({ workData: workData.id_work_data })} className="inline-flex items-center gap-2 text-sm text-neutral-500 hover:text-[#0071b7]"><ArrowLeft className="size-4" />Back to Workers</Link><div className="rounded-2xl bg-linear-to-br from-[#0071b7] via-[#0089cc] to-[#0093dd] p-8 shadow-lg"><h1 className="text-3xl font-bold text-white">{pekerja ? 'Edit Worker' : 'Add Worker'}</h1><p className="mt-2 text-sm text-white/80">{workData.no_kerja}</p></div><Form method="post" action={pekerja ? pekerjaUpdate.url({ workData: workData.id_work_data, pekerja: pekerja.id_work_data_pekerja! }) : pekerjaStore.url({ workData: workData.id_work_data })} className="space-y-6 rounded-2xl border border-neutral-200/60 bg-white p-6 shadow-sm dark:border-neutral-800 dark:bg-neutral-900">{({ processing, errors }) => <><input type="hidden" name="_method" value={pekerja ? 'PUT' : 'POST'} /><div className="grid gap-4 sm:grid-cols-2"><div><Label htmlFor="id_employee">Employee ID</Label><Input id="id_employee" name="id_employee" defaultValue={pekerja?.id_employee || ''} className="mt-1" />{errors.id_employee && <p className="text-xs text-red-500">{errors.id_employee}</p>}</div><div><Label htmlFor="id_user">User ID</Label><Input id="id_user" name="id_user" type="number" defaultValue={pekerja?.id_user ?? ''} className="mt-1" /></div><div><Label>Role</Label><select name="role_pekerja" defaultValue={pekerja?.role_pekerja || 'pelaksana'} className="mt-1 w-full rounded-lg border px-3 py-2 dark:border-neutral-700 dark:bg-neutral-800 dark:text-white">{roles.map(x => <option key={x}>{x}</option>)}</select></div><div><Label>Status</Label><select name="status_alokasi" defaultValue={pekerja?.status_alokasi || 'assigned'} className="mt-1 w-full rounded-lg border px-3 py-2 dark:border-neutral-700 dark:bg-neutral-800 dark:text-white">{statuses.map(x => <option key={x}>{x}</option>)}</select></div></div><div><Label htmlFor="catatan">Catatan</Label><Textarea id="catatan" name="catatan" defaultValue={pekerja?.catatan || ''} className="mt-1" rows={4} /></div><div className="flex justify-end"><Button disabled={processing} className="bg-linear-to-r from-[#0071b7] to-[#0093dd]">{processing ? 'Saving...' : 'Save Worker'}</Button></div></>}</Form></div></>; }
PekerjaCreate.layout = { breadcrumbs: [{ title: 'Work Data', href: '/work-data' }, { title: 'Workers', href: '' }, { title: 'Add', href: '' }] };
