import { Head, Link, router } from '@inertiajs/react';
import { ArrowLeft, Edit, Plus, Trash2, Users } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { index as pekerjaIndex, create as pekerjaCreate, edit as pekerjaEdit, destroy as pekerjaDestroy } from '@/routes/work-data/pekerja';

type WorkDataWithDept = { id_work_data: number; no_kerja: string; department?: { nama_department: string } | null };
type WorkDataPekerja = { id_work_data_pekerja: number; id_work_data: number; id_employee: string | null; id_user: number | null; role_pekerja: string; status_alokasi: string; catatan: string | null; accepted_at: string | null; completed_at: string | null; employee?: { nama_employee: string } | null; user?: { name: string } | null };
type PaginatedList<T> = { data: T[]; current_page: number; last_page: number; per_page: number; total: number; from: number; to: number };
type Filters = { status_alokasi?: string };
type Props = { workData: WorkDataWithDept; pekerja: PaginatedList<WorkDataPekerja>; filters: Filters };
const statuses = ['assigned', 'accepted', 'in_progress', 'completed'];
const badgeClass: Record<string, string> = { assigned: 'bg-neutral-100 text-neutral-700 dark:bg-neutral-800 dark:text-neutral-300', accepted: 'bg-blue-100 text-blue-700 dark:bg-blue-500/20 dark:text-blue-400', in_progress: 'bg-yellow-100 text-yellow-700 dark:bg-yellow-500/20 dark:text-yellow-400', completed: 'bg-green-100 text-green-700 dark:bg-green-500/20 dark:text-green-400' };
const label = (value: string) => value.replace(/_/g, ' ');

export default function PekerjaIndex({ workData, pekerja, filters }: Props) {
    const filter = filters.status_alokasi || '';
    const changeFilter = (value: string) => router.get(pekerjaIndex.url({ workData: workData.id_work_data }), { status_alokasi: value || undefined }, { preserveState: true, preserveScroll: true });
    return <><Head title={`Workers - ${workData.no_kerja}`} /><div className="mx-auto w-full max-w-7xl space-y-6">
        <Link href={`/work-data/${workData.id_work_data}`} className="inline-flex items-center gap-2 text-sm text-neutral-500 hover:text-[#0071b7]"><ArrowLeft className="size-4" />Back to Work Data</Link>
        <div className="relative overflow-hidden rounded-2xl bg-linear-to-br from-[#0071b7] via-[#0089cc] to-[#0093dd] p-8 shadow-lg"><div className="relative flex items-center justify-between"><div><p className="mb-2 text-sm text-white/80">Worker Allocation</p><h1 className="text-3xl font-bold text-white">{workData.no_kerja}</h1><p className="mt-2 text-sm text-white/80">{workData.department?.nama_department || 'Work data workers'}</p></div><Link href={pekerjaCreate.url({ workData: workData.id_work_data })}><Button className="bg-white text-[#0071b7] hover:bg-white/90"><Plus className="size-4" />Add Worker</Button></Link></div></div>
        <div className="grid gap-4 sm:grid-cols-2"><div className="rounded-2xl border border-neutral-200/60 bg-white p-6 shadow-sm dark:border-neutral-800 dark:bg-neutral-900"><p className="text-sm text-neutral-500">Total Workers</p><p className="mt-1 text-2xl font-bold dark:text-white">{pekerja.total}</p></div><div className="rounded-2xl border border-neutral-200/60 bg-white p-6 shadow-sm dark:border-neutral-800 dark:bg-neutral-900"><p className="text-sm text-neutral-500">Current Filter</p><p className="mt-1 text-2xl font-bold capitalize text-[#0071b7]">{filter ? label(filter) : 'All'}</p></div></div>
        <div className="rounded-2xl border border-neutral-200/60 bg-white p-6 shadow-sm dark:border-neutral-800 dark:bg-neutral-900"><label className="text-sm font-medium dark:text-white">Status</label><select value={filter} onChange={e => changeFilter(e.target.value)} className="mt-2 w-full max-w-xs rounded-lg border border-neutral-300 bg-white px-3 py-2 text-sm dark:border-neutral-700 dark:bg-neutral-800 dark:text-white"><option value="">All Status</option>{statuses.map(s => <option key={s} value={s}>{label(s)}</option>)}</select></div>
        <div className="overflow-x-auto rounded-2xl border border-neutral-200/60 bg-white p-6 shadow-sm dark:border-neutral-800 dark:bg-neutral-900"><table className="w-full text-left text-sm"><thead><tr className="border-b dark:border-neutral-700"><th className="p-3">Employee Name</th><th className="p-3">Role</th><th className="p-3">Status</th><th className="p-3 text-right">Actions</th></tr></thead><tbody>{pekerja.data.map(item => <tr key={item.id_work_data_pekerja} className="border-b last:border-0 dark:border-neutral-800"><td className="p-3 font-medium dark:text-white">{item.employee?.nama_employee || item.user?.name || item.id_employee || item.id_user || '-'}</td><td className="p-3 capitalize dark:text-neutral-300">{item.role_pekerja}</td><td className="p-3"><Badge className={`capitalize ${badgeClass[item.status_alokasi] || ''}`}>{label(item.status_alokasi)}</Badge></td><td className="p-3"><div className="flex justify-end gap-2"><Link href={pekerjaEdit.url({ workData: workData.id_work_data, pekerja: item.id_work_data_pekerja })}><Button size="sm" variant="outline"><Edit className="size-4" />Edit</Button></Link><Button size="sm" variant="destructive" onClick={() => window.confirm('Delete this worker allocation?') && router.delete(pekerjaDestroy.url({ workData: workData.id_work_data, pekerja: item.id_work_data_pekerja }))}><Trash2 className="size-4" />Delete</Button></div></td></tr>)}</tbody></table>{pekerja.data.length === 0 && <p className="py-8 text-center text-sm text-neutral-500">No workers allocated.</p>}</div>
    </div></>;
}
PekerjaIndex.layout = { breadcrumbs: [{ title: 'Work Data', href: '/work-data' }, { title: 'Workers', href: '' }] };
